# wrangler.toml configuration for Otaku Insider Pages

minify = true
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[site]
bucket = ".vercel/output/static"

[build]
command = "npx --legacy-peer-deps @cloudflare/next-on-pages@1"
path = ".vercel/output"

